video_capture_settings_a:
    camera_port: 0
    fps: 30
    height: 1024
    width: 1280
    filter_blank: true
    filter_blank_std_dev_threshold: 5
    publish_cropped: true
    publish_uncropped: false
video_capture_settings_b:
    camera_port: 1
    fps: 30
    height: 1024
    width: 1280
    filter_blank: true
    filter_blank_std_dev_threshold: 5
    publish_cropped: true
    publish_uncropped: false
mono_tracker_a_settings:
  filter_options:
    largest: true
    most_confident: false
    confidence_threshold: 0.5
    max_pixels: null
    min_pixels: null
    max_major_axis_length: null
    min_major_axis_length: null
  model_path_override: null
  fallback_to_available_providers: false
  startup_timeout_s: 30.0
  operational_timeout_s: 1
  initial_orientation: 90
mono_tracker_b_settings:
  filter_options:
    largest: true
    most_confident: false
    confidence_threshold: 0.5
    max_pixels: null
    min_pixels: null
    max_major_axis_length: null
    min_major_axis_length: null
  model_path_override: null
  fallback_to_available_providers: false
  startup_timeout_s: 30.0
  operational_timeout_s: 1
  initial_orientation: 135
stereo_settings:
  detector_max_delay_ms: 500
  noise_detection: true
  blade_reprojection_error_threshold: 10000000
  centroid_reprojection_error_threshold: 15
  centroid_diff_in_pixels_threshold: 2
overlay_settings:
  bot_detection_2d_line_color: [0, 255, 255]
  bot_detection_reprojected_blade_color: [0, 0, 255]
  bot_detection_reprojected_centroid_color: [255, 0, 0]
  bot_detection_reprojected_line_color: [0, 255, 0]
  bot_detection_reprojected_tail_color: [255, 0, 255]
  epiline_color: [0, 255, 255]
  ptv_line_alpha: 0.2
  ptv_line_color: [0, 255, 0]
  safeRangeLine_color: [0, 255, 0]
  show_bot_detection_2d: true
  show_bot_detection_reprojected: true
  show_epiline: true
  show_ptv: true
  show_safe_range_lines: true
  show_treatment_sphere: true
  trajectory_lines_color: [51, 204, 204]
  treatment_sphere_alpha: 0.1
  treatment_sphere_color: [255, 177, 130]
